language: cpp

env:
  global:
    - DEPS_DIR=${TRAVIS_BUILD_DIR}/deps

matrix:
  include:
    - os: linux
      dist: bionic
      addons:
        apt:
          packages:
            - gcc-8
            - g++-8
      env:
        - MATRIX_EVAL="CC=gcc-8 && CXX=g++-8 && CXX_FLAGS="
    - os: linux
      dist: bionic
      addons:
        apt:
          packages:
            - clang-9
            - libc++-9-dev
            - libc++abi-9-dev
      env:
        - MATRIX_EVAL="CC=clang-9 && CXX=clang++-9 && CXX_FLAGS=-stdlib=libc++"

before_install:
  - eval "${MATRIX_EVAL}"

install:
  - |
    if [[ ${TRAVIS_OS_NAME} == "linux" ]]; then
      CMAKE_URL="https://github.com/Kitware/CMake/releases/download/v3.16.5/cmake-3.16.5-Linux-x86_64.tar.gz"
      mkdir -p ${DEPS_DIR}/cmake
      travis_retry wget --no-check-certificate --quiet -O - ${CMAKE_URL} | tar --strip-components=1 -xz -C ${DEPS_DIR}/cmake
      export PATH=${DEPS_DIR}/cmake/bin:${PATH}
    fi

script:
  - ${CXX} --version
  - cmake --version
  - mkdir -p build
  - cd build
  - cmake -DCMAKE_CXX_FLAGS=${CXX_FLAGS} ..
  - cmake --build . --verbose