version: 0.1.0.{build}-{branch}

environment:
  matrix:
    - platform: x64
      image: Visual Studio 2017
      configuration: Debug
    - platform: x64
      image: Visual Studio 2017
      configuration: Release
    - platform: x64
      image: Visual Studio 2019
      configuration: Debug
    - platform: x64
      image: Visual Studio 2019
      configuration: Release

before_build:
  - mkdir build
  - cd build
  - if "%APPVEYOR_BUILD_WORKER_IMAGE%" == "Visual Studio 2017" (
      cmake -G "Visual Studio 15 2017 Win64" ..
    ) else if "%APPVEYOR_BUILD_WORKER_IMAGE%" == "Visual Studio 2019" (
      cmake -G "Visual Studio 16 2019" ..
    )

build_script:
  - cmake --build . --verbose --config %CONFIGURATION%

test_script:
  - ctest --verbose -C %CONFIGURATION%