version: 0.3.2.{build}-{branch}

configuration:
  - Debug

platform:
  - x64

environment:
  matrix:
    - job_name: VS 2017 build
      appveyor_build_worker_image: Visual Studio 2017
    - job_name: VS 2019 build
      appveyor_build_worker_image: Visual Studio 2019

matrix:
  fast_finish: true

cache: C:/Tools/vcpkg/installed/

before_build:
  - vcpkg install libpng:x64-windows
  - mkdir build
  - cd build

for:
  -
    matrix:
      only:
        - job_name: VS 2017 build

    build_script:
    - cmd: cmake -DCMAKE_TOOLCHAIN_FILE=C:/Tools/vcpkg/scripts/buildsystems/vcpkg.cmake -G "Visual Studio 15 2017 Win64" ..
    - cmd: cmake --build . --verbose --config %CONFIGURATION%

  -
    matrix:
      only:
        - job_name: VS 2019 build

    build_script:
    - cmd: cmake -DCMAKE_TOOLCHAIN_FILE=C:/Tools/vcpkg/scripts/buildsystems/vcpkg.cmake -G "Visual Studio 16 2019" ..
    - cmd: cmake --build . --verbose --config %CONFIGURATION%

test_script:
- cmd: ctest --verbose -C %CONFIGURATION%
