version: 1.6.2.{build}-{branch}

configuration: Debug
platform: x64

environment:
  matrix:
    - job_name: Linux (GCC)
      APPVEYOR_BUILD_WORKER_IMAGE: Ubuntu2004
    - job_name: Windows (MSVC)
      APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2022
    - job_name: Mac OSX (Clang)
      APPVEYOR_BUILD_WORKER_IMAGE: macOS-BigSur

matrix:
  fast_finish: true

install:
  - sh: git submodule update --init --recursive
  - cmd: git submodule update --init --recursive

before_build:
  - ps: mkdir artifacts
  - ps: mkdir build
  - ps: cd build

for:
  -
    matrix:
      only:
        - job_name: Linux (GCC)

    cache: $HOME/boost_1_81_0 -> appveyor_files/install_boost.sh

    build_script:
    - sh: sudo apt -y install g++-10 libgl1-mesa-dev
    - sh: ../appveyor_files/install_boost.sh
    - sh: cmake -DPACKAGE_TESTS=OFF -DCMAKE_CXX_COMPILER=g++-10 -DBOOST_ROOT=$HOME/boost_1_81_0 -DQt6_DIR=$HOME/Qt/6.4/gcc_64/lib/cmake/Qt6 -DQt6CoreTools_DIR=$HOME/Qt/6.4/gcc_64/lib/cmake/Qt6CoreTools -DQt6DBusTools_DIR=$HOME/Qt/6.4/gcc_64/lib/cmake/Qt6DBusTools -DQt6GuiTools_DIR=$HOME/Qt/6.4/gcc_64/lib/cmake/Qt6GuiTools -DQt6WidgetsTools_DIR=$HOME/Qt/6.4/gcc_64/lib/cmake/Qt6WidgetsTools ..
    - sh: cmake --build . --verbose --config ${CONFIGURATION}

    before_deploy:
    - sh: export RELEASE_NAME=${APPVEYOR_REPO_TAG_NAME#v}
    - sh: rm -rf *
    - sh: cmake -DCMAKE_CXX_COMPILER=g++-10 -DENABLE_LTO=ON -DPACKAGE_TESTS=OFF -DBOOST_ROOT=$HOME/boost_1_81_0 -DBoost_USE_STATIC_LIBS=ON -DQt6_DIR=$HOME/Qt/6.4/gcc_64/lib/cmake/Qt6 -DQt6CoreTools_DIR=$HOME/Qt/6.4/gcc_64/lib/cmake/Qt6CoreTools -DQt6DBusTools_DIR=$HOME/Qt/6.4/gcc_64/lib/cmake/Qt6DBusTools -DQt6GuiTools_DIR=$HOME/Qt/6.4/gcc_64/lib/cmake/Qt6GuiTools -DQt6WidgetsTools_DIR=$HOME/Qt/6.4/gcc_64/lib/cmake/Qt6WidgetsTools ..
    - sh: cmake --build . --verbose --config Release
    - sh: strip -s chopt
    - sh: strip -s choptgui
    - sh: mv chopt CHOpt
    - sh: zip "../artifacts/CHOpt CLI ${RELEASE_NAME} (x64 Linux).zip" CHOpt
    - sh: mv choptgui CHOpt
    - sh: mkdir libs
    - sh: mkdir platforms
    - sh: cp ../resources/CHOpt.sh CHOpt.sh
    - sh: cp $HOME/Qt/6.4/gcc_64/lib/libicudata.so.56 libs/libicudata.so.56
    - sh: cp $HOME/Qt/6.4/gcc_64/lib/libicui18n.so.56 libs/libicui18n.so.56
    - sh: cp $HOME/Qt/6.4/gcc_64/lib/libicuuc.so.56 libs/libicuuc.so.56
    - sh: cp $HOME/Qt/6.4/gcc_64/lib/libQt6Core.so.6 libs/libQt6Core.so.6
    - sh: cp $HOME/Qt/6.4/gcc_64/lib/libQt6DBus.so.6 libs/libQt6DBus.so.6
    - sh: cp $HOME/Qt/6.4/gcc_64/lib/libQt6Gui.so.6 libs/libQt6Gui.so.6
    - sh: cp $HOME/Qt/6.4/gcc_64/lib/libQt6OpenGL.so.6 libs/libQt6OpenGL.so.6
    - sh: cp $HOME/Qt/6.4/gcc_64/lib/libQt6Widgets.so.6 libs/libQt6Widgets.so.6
    - sh: cp $HOME/Qt/6.4/gcc_64/lib/libQt6XcbQpa.so.6 libs/libQt6XcbQpa.so.6
    - sh: cp $HOME/Qt/6.4/gcc_64/plugins/platforms/libqxcb.so platforms/libqxcb.so
    - sh: zip -r "../artifacts/CHOpt ${RELEASE_NAME} (x64 Linux).zip" CHOpt CHOpt.sh libs platforms
    - sh: appveyor PushArtifact "../artifacts/CHOpt CLI ${RELEASE_NAME} (x64 Linux).zip"
    - sh: appveyor PushArtifact "../artifacts/CHOpt ${RELEASE_NAME} (x64 Linux).zip"

  -
    matrix:
      only:
        - job_name: Windows (MSVC)

    cache: C:\Tools\vcpkg\archives

    environment:
      VCPKG_DEFAULT_BINARY_CACHE: C:\Tools\vcpkg\archives
      LOG_DIR: C:\Users\appveyor\AppData\Local\Temp\1\build-cache-logs

    build_script:
    - ps: if (-Not (Test-Path C:\Tools\vcpkg\archives)) { mkdir C:\Tools\vcpkg\archives }
    - ps: vcpkg --triplet x64-windows install libpng
    - ps: cmake -DCMAKE_TOOLCHAIN_FILE=C:\Tools\vcpkg\scripts\buildsystems\vcpkg.cmake -DPACKAGE_TESTS=OFF -DBOOST_ROOT=C:\Libraries\boost_1_83_0 -DBoost_USE_STATIC_LIBS=ON -DQt6_DIR=C:\Qt\6.4\msvc2019_64\lib\cmake\Qt6 -DQt6CoreTools_DIR=C:\Qt\6.4\msvc2019_64\lib\cmake\Qt6CoreTools -DQt6GuiTools_DIR=C:\Qt\6.4\msvc2019_64\lib\cmake\Qt6GuiTools -DQt6WidgetsTools_DIR=C:\Qt\6.4\msvc2019_64\lib\cmake\Qt6WidgetsTools -G "Visual Studio 17 2022" ..
    - ps: cmake --build . --verbose --config $env:CONFIGURATION

    before_deploy:
    - ps: $RELEASE_NAME = $env:APPVEYOR_REPO_TAG_NAME.TrimStart("v")
    - ps: cmake -DENABLE_LTO=ON -DPACKAGE_TESTS=OFF -DQt6_DIR=C:\Qt\6.4\msvc2019_64\lib\cmake\Qt6 -DQt6CoreTools_DIR=C:\Qt\6.4\msvc2019_64\lib\cmake\Qt6CoreTools -DQt6GuiTools_DIR=C:\Qt\6.4\msvc2019_64\lib\cmake\Qt6GuiTools -DQt6WidgetsTools_DIR=C:\Qt\6.4\msvc2019_64\lib\cmake\Qt6WidgetsTools -G "Visual Studio 17 2022" ..
    - ps: cmake --build . --verbose --config Release
    - ps: cd Release
    - ps: Rename-Item chopt.exe CHOpt.exe
    - ps: Move-Item choptgui.exe ..\choptgui.exe
    - ps: 7z a "..\artifacts\CHOpt CLI ${RELEASE_NAME} (x64 Windows).zip" *
    - ps: del CHOpt.exe
    - ps: Move-Item ..\choptgui.exe CHOpt.exe
    - ps: $env:VCINSTALLDIR = "C:\Program Files\Microsoft Visual Studio\2022\Community\VC"
    - ps: C:\Qt\6.4\msvc2019_64\bin\windeployqt.exe --release --no-opengl-sw --no-svg --no-system-d3d-compiler --no-translations CHOpt.exe
    - ps: rm vc_redist.x64.exe
    - ps: 7z a "..\artifacts\CHOpt ${RELEASE_NAME} (x64 Windows).zip" *
    - ps: Push-AppveyorArtifact "..\artifacts\CHOpt CLI ${RELEASE_NAME} (x64 Windows).zip"
    - ps: Push-AppveyorArtifact "..\artifacts\CHOpt ${RELEASE_NAME} (x64 Windows).zip"

    on_finish:
    - ps: if (Test-Path -Path $env:LOG_DIR) { Get-ChildItem $env:LOG_DIR\*.log | % { Push-AppveyorArtifact $_.FullName -FileName $_.Name } }

  -
    matrix:
      only:
        - job_name: Mac OSX (Clang)

    build_script:
    - sh: brew install boost libpng
    - sh: cmake -DCMAKE_CXX_COMPILER=clang++ -DPACKAGE_TESTS=OFF -DCMAKE_FIND_FRAMEWORK=LAST -DQt6_DIR=$HOME/Qt/6.2/macos/lib/cmake/Qt6 -DQt6CoreTools_DIR=$HOME/Qt/6.2/macos/lib/cmake/Qt6CoreTools -DQt6DBusTools_DIR=$HOME/Qt/6.2/macos/lib/cmake/Qt6DBusTools -DQt6GuiTools_DIR=$HOME/Qt/6.2/macos/lib/cmake/Qt6GuiTools -DQt6WidgetsTools_DIR=$HOME/Qt/6.2/macos/lib/cmake/Qt6WidgetsTools ..
    - sh: cmake --build . --verbose --config ${CONFIGURATION}

    before_deploy:
    - sh: export RELEASE_NAME=${APPVEYOR_REPO_TAG_NAME#v}
    - sh: rm -rf *
    - sh: cmake -DCMAKE_CXX_COMPILER=clang++ -DENABLE_LTO=ON -DPACKAGE_TESTS=OFF -DBoost_USE_STATIC_LIBS=ON -DCMAKE_FIND_FRAMEWORK=LAST -DQt6_DIR=$HOME/Qt/6.2/macos/lib/cmake/Qt6 -DQt6CoreTools_DIR=$HOME/Qt/6.2/macos/lib/cmake/Qt6CoreTools -DQt6DBusTools_DIR=$HOME/Qt/6.2/macos/lib/cmake/Qt6DBusTools -DQt6GuiTools_DIR=$HOME/Qt/6.2/macos/lib/cmake/Qt6GuiTools -DQt6WidgetsTools_DIR=$HOME/Qt/6.2/macos/lib/cmake/Qt6WidgetsTools ..
    - sh: cmake --build . --verbose --config Release
    - sh: strip -x chopt
    - sh: mv chopt CHOpt
    - sh: install_name_tool -change /usr/local/opt/libpng/lib/libpng16.16.dylib @executable_path/libpng16.16.dylib CHOpt
    - sh: cp /usr/local/Cellar/libpng/1.6.39/lib/libpng16.16.dylib libpng16.16.dylib
    - sh: zip -r "../artifacts/CHOpt CLI ${RELEASE_NAME} (x64 Mac).zip" CHOpt libpng16.16.dylib
    - sh: mv choptgui.app CHOpt.app
    - sh: mv CHOpt.app/Contents/MacOS/choptgui CHOpt.app/Contents/MacOS/CHOpt
    - sh: sed -i '' 's/choptgui/CHOpt/g' CHOpt.app/Contents/Info.plist
    - sh: $HOME/Qt/6.2/macos/bin/macdeployqt CHOpt.app
    - sh: zip -r "../artifacts/CHOpt ${RELEASE_NAME} (x64 Mac).zip" CHOpt.app
    - sh: appveyor PushArtifact "../artifacts/CHOpt CLI ${RELEASE_NAME} (x64 Mac).zip"
    - sh: appveyor PushArtifact "../artifacts/CHOpt ${RELEASE_NAME} (x64 Mac).zip"

deploy:
  provider: Environment
  name: Staging
  artifact:
  on:
    APPVEYOR_REPO_TAG: true
