version: 0.1.0.{build}-{branch}

image:
  - Visual Studio 2017
  - Visual Studio 2019

platform:
  - x64

configuration:
  - Debug
  - Release

before_build:
  - mkdir build
  - cd build
  - echo %APPVEYOR_BUILD_WORKER_IMAGE%
  - if "%APPVEYOR_BUILD_WORKER_IMAGE%" == "Visual Studio 2017" (echo "A") else if "%APPVEYOR_BUILD_WORKER_IMAGE%" == "Visual Studio 2019" (echo "B")

test_script:
  - ctest --verbose -C %CONFIGURATION%