version: 0.1.0.{build}-{branch}

image:
  - Visual Studio 2017
  - Visual Studio 2019

configuration:
  - Debug
  - Release

platform:
  - x64

environment:
  matrix:
    - COMPILER: Visual Studio
    - COMPILER: Clang

before_build:
  - mkdir build
  - cd build
  - if "%COMPILER%" == "Clang" (
      cmake -DCMAKE_BUILD_TYPE=%CONFIGURATION% -DCMAKE_CXX_COMPILER=clang -G Ninja ..
    ) else if "%COMPILER%" == "Visual Studio" (
      if "%APPVEYOR_BUILD_WORKER_IMAGE%" == "Visual Studio 2017" (
        cmake -G "Visual Studio 15 2017 Win64" ..
      ) else if "%APPVEYOR_BUILD_WORKER_IMAGE%" == "Visual Studio 2019" (
        cmake -G "Visual Studio 16 2019" ..
      )
    )

build_script:
  - if "%COMPILER%" == "Clang" (
      cmake --build . --verbose
    ) else if "%COMPILER%" == "Visual Studio" (
      cmake --build . --verbose --config %CONFIGURATION%
    )

test_script:
  - if "%COMPILER%" == "Clang" (
      ctest --verbose
    ) else if "%COMPILER%" == "Visual Studio" (
      ctest --verbose -C %CONFIGURATION%
    )