version: 0.3.2.{build}-{branch}

configuration:
  - Debug

platform:
  - x64

environment:
  matrix:
    - job_name: VS 2017 build
      appveyor_build_worker_image: Visual Studio 2017
    - job_name: VS 2019 build
      appveyor_build_worker_image: Visual Studio 2019
    - job_name: Clang build
      appveyor_build_worker_image: Visual Studio 2019
    - job_name: MinGW build
      appveyor_build_worker_image: Visual Studio 2019

matrix:
  fast_finish: true

cache: c:\tools\vcpkg\installed\

before_build:
  - vcpkg install zlib:x64-windows
  - cd c:\tools\vcpkg
  - vcpkg integrate install
  - cd C:\projects\chopt
  - mkdir build
  - cd build

for:
  -
    matrix:
      only:
        - job_name: VS 2017 build

    build_script:
    - cmd: cmake -G "Visual Studio 15 2017 Win64" ..
    - cmd: cmake --build . --verbose --config %CONFIGURATION%

    test_script:
    - cmd: ctest --verbose -C %CONFIGURATION%

  -
    matrix:
      only:
        - job_name: VS 2019 build

    build_script:
    - cmd: cmake -G "Visual Studio 16 2019" ..
    - cmd: cmake --build . --verbose --config %CONFIGURATION%

    test_script:
    - cmd: ctest --verbose -C %CONFIGURATION%

  -
    matrix:
      only:
        - job_name: Clang build

    build_script:
    - cmd: cmake -DCMAKE_BUILD_TYPE=%CONFIGURATION% -DCMAKE_CXX_COMPILER=Clang -G Ninja ..
    - cmd: cmake --build . --verbose

    test_script:
    - cmd: ctest --verbose

  -
    matrix:
      only:
        - job_name: MinGW build

    build_script:
    - cmd: set "PATH=C:/mingw-w64/x86_64-8.1.0-posix-seh-rt_v6-rev0/mingw64/bin;%PATH%"
    - cmd: cmake -DCMAKE_BUILD_TYPE=%CONFIGURATION% -DCMAKE_CXX_COMPILER=g++ -G Ninja ..
    - cmd: cmake --build . --verbose

    test_script:
    - cmd: ctest --verbose
