version: 0.1.0.{build}-{branch}

image:
  - Visual Studio 2017
  - Visual Studio 2019

platform:
  - x64

configuration:
  - Debug
  - Release

before_build:
  - mkdir build
  - cd build
  - if %APPVEYOR_BUILD_WORKER_IMAGE% == "Visual Studio 2017" (
      cmake -G "Visual Studio 15 2017 Win64" ..
    ) ELSE IF %APPVEYOR_BUILD_WORKER_IMAGE% == "Visual Studio 2019" (
      cmake -G "Visual Studio 16 2019"
    )

test_script:
  - ctest --verbose -C %CONFIGURATION%