version: 1.7.0.{build}-{branch}

configuration: Debug
platform: x64

environment:
  matrix:
    - job_name: Linux (GCC)
      APPVEYOR_BUILD_WORKER_IMAGE: Ubuntu2004

matrix:
  fast_finish: true

install:
  - sh: git submodule update --init --recursive

before_build:
  - ps: mkdir artifacts
  - ps: mkdir build
  - ps: cd build

for:
  -
    matrix:
      only:
        - job_name: Linux (GCC)

    cache: $HOME/boost_1_81_0 -> appveyor_files/install_boost.sh

    build_script:
    - sh: sudo apt -y install g++-10 libgl1-mesa-dev
    - sh: ../appveyor_files/install_boost.sh
    - sh: cmake -DPACKAGE_TESTS=OFF -DCMAKE_CXX_COMPILER=g++-10 -DBOOST_ROOT=$HOME/boost_1_81_0 -DQt6_DIR=$HOME/Qt/6.4/gcc_64/lib/cmake/Qt6 -DQt6CoreTools_DIR=$HOME/Qt/6.4/gcc_64/lib/cmake/Qt6CoreTools -DQt6DBusTools_DIR=$HOME/Qt/6.4/gcc_64/lib/cmake/Qt6DBusTools -DQt6GuiTools_DIR=$HOME/Qt/6.4/gcc_64/lib/cmake/Qt6GuiTools -DQt6WidgetsTools_DIR=$HOME/Qt/6.4/gcc_64/lib/cmake/Qt6WidgetsTools ..
    - sh: cmake --build . --verbose --config ${CONFIGURATION}

    before_deploy:
    - sh: export RELEASE_NAME=${APPVEYOR_REPO_TAG_NAME#v}
    - sh: rm -rf *
    - sh: cmake -DCMAKE_CXX_COMPILER=g++-10 -DENABLE_LTO=ON -DPACKAGE_TESTS=OFF -DBOOST_ROOT=$HOME/boost_1_81_0 -DBoost_USE_STATIC_LIBS=ON -DQt6_DIR=$HOME/Qt/6.4/gcc_64/lib/cmake/Qt6 -DQt6CoreTools_DIR=$HOME/Qt/6.4/gcc_64/lib/cmake/Qt6CoreTools -DQt6DBusTools_DIR=$HOME/Qt/6.4/gcc_64/lib/cmake/Qt6DBusTools -DQt6GuiTools_DIR=$HOME/Qt/6.4/gcc_64/lib/cmake/Qt6GuiTools -DQt6WidgetsTools_DIR=$HOME/Qt/6.4/gcc_64/lib/cmake/Qt6WidgetsTools ..
    - sh: cmake --build . --verbose --config Release
    - sh: strip -s chopt
    - sh: strip -s choptgui
    - sh: mv chopt CHOpt
    - sh: zip "../artifacts/CHOpt CLI ${RELEASE_NAME} (x64 Linux).zip" CHOpt
    - sh: mv choptgui CHOpt
    - sh: mkdir libs
    - sh: mkdir platforms
    - sh: cp ../resources/CHOpt.sh CHOpt.sh
    - sh: cp $HOME/Qt/6.4/gcc_64/lib/libicudata.so.56 libs/libicudata.so.56
    - sh: cp $HOME/Qt/6.4/gcc_64/lib/libicui18n.so.56 libs/libicui18n.so.56
    - sh: cp $HOME/Qt/6.4/gcc_64/lib/libicuuc.so.56 libs/libicuuc.so.56
    - sh: cp $HOME/Qt/6.4/gcc_64/lib/libQt6Core.so.6 libs/libQt6Core.so.6
    - sh: cp $HOME/Qt/6.4/gcc_64/lib/libQt6DBus.so.6 libs/libQt6DBus.so.6
    - sh: cp $HOME/Qt/6.4/gcc_64/lib/libQt6Gui.so.6 libs/libQt6Gui.so.6
    - sh: cp $HOME/Qt/6.4/gcc_64/lib/libQt6OpenGL.so.6 libs/libQt6OpenGL.so.6
    - sh: cp $HOME/Qt/6.4/gcc_64/lib/libQt6Widgets.so.6 libs/libQt6Widgets.so.6
    - sh: cp $HOME/Qt/6.4/gcc_64/lib/libQt6XcbQpa.so.6 libs/libQt6XcbQpa.so.6
    - sh: cp $HOME/Qt/6.4/gcc_64/plugins/platforms/libqxcb.so platforms/libqxcb.so
    - sh: zip -r "../artifacts/CHOpt ${RELEASE_NAME} (x64 Linux).zip" CHOpt CHOpt.sh libs platforms
    - sh: appveyor PushArtifact "../artifacts/CHOpt CLI ${RELEASE_NAME} (x64 Linux).zip"
    - sh: appveyor PushArtifact "../artifacts/CHOpt ${RELEASE_NAME} (x64 Linux).zip"

deploy:
  provider: Environment
  name: Staging
  artifact:
  on:
    APPVEYOR_REPO_TAG: true
