version: 1.4.0.{build}-{branch}

configuration: Debug
platform: x64

environment:
  matrix:
    - job_name: Windows (MSVC, tests, and static analysis)
      APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2019
    - job_name: Mac OSX (Clang)
      APPVEYOR_BUILD_WORKER_IMAGE: macOS-BigSur
    - job_name: Linux (GCC)
      APPVEYOR_BUILD_WORKER_IMAGE: Ubuntu2004

matrix:
  fast_finish: true

before_build:
  - cmd: vcpkg install libpng:x64-windows
  - ps: mkdir build
  - ps: cd build

for:
  -
    matrix:
      only:
        - job_name: Windows (MSVC, tests, and static analysis)

    cache: C:/Tools/vcpkg/installed/

    build_script:
    - cmd: cmake -DCMAKE_TOOLCHAIN_FILE=C:/Tools/vcpkg/scripts/buildsystems/vcpkg.cmake -DQt6_DIR=C:/Qt/6.2.1/msvc2019_64/lib/cmake/Qt6 -DQt6CoreTools_DIR=C:/Qt/6.2.1/msvc2019_64/lib/cmake/Qt6CoreTools -DQt6GuiTools_DIR=C:/Qt/6.2.1/msvc2019_64/lib/cmake/Qt6GuiTools -DQt6WidgetsTools_DIR=C:/Qt/6.2.1/msvc2019_64/lib/cmake/Qt6WidgetsTools -G "Visual Studio 16 2019" ..
    - cmd: cmake --build . --verbose --config %CONFIGURATION%

    test_script:
    - cmd: ctest --verbose -C %CONFIGURATION%
    - cmd: cd ..
    - cmd: set PATH=C:/Python39-x64;C:/Python39-x64/Scripts;%PATH%
    - cmd: python integration_tests/run_integration_tests.py
    - cmd: clang-format -i gui/*.hpp gui/*.cpp include/*.hpp src/*.cpp tests/*.cpp
    - cmd: git diff --color --exit-code
    - cmd: clang-tidy src/*.cpp -- -Iinclude -Ilibs -Ibuild/_deps/argparse-src/include -Ibuild/_deps/nowide-src/include -IC:/Tools/vcpkg/installed/x64-windows/include -std=c++17
    - cmd: clang-tidy tests/*.cpp -checks=-cppcoreguidelines-avoid-magic-numbers,-readability-function-cognitive-complexity,-readability-magic-numbers -- -Iinclude -Ilibs -Ibuild/_deps/nowide-src/include -IC:/Tools/vcpkg/installed/x64-windows/include -std=c++17

  -
    matrix:
      only:
        - job_name: Mac OSX (Clang)

    build_script:
    - sh: brew install libpng
    - sh: cmake -DCMAKE_CXX_COMPILER=clang++ -DQt6_DIR=$HOME/Qt/6.2.0/macos/lib/cmake/Qt6 -DQt6CoreTools_DIR=$HOME/Qt/6.2.0/macos/lib/cmake/Qt6CoreTools -DQt6GuiTools_DIR=$HOME/Qt/6.2.0/macos/lib/cmake/Qt6GuiTools -DQt6WidgetsTools_DIR=$HOME/Qt/6.2.0/macos/lib/cmake/Qt6WidgetsTools ..
    - sh: cmake --build . --verbose --config ${CONFIGURATION}

  -
    matrix:
      only:
        - job_name: Linux (GCC)

    build_script:
    - sh: sudo apt update
    - sh: sudo apt -y install libgl1-mesa-dev
    - sh: cmake -DCMAKE_CXX_COMPILER=g++-9 -DQt6_DIR=$HOME/Qt/6.2.1/gcc_64/lib/cmake/Qt6 -DQt6CoreTools_DIR=$HOME/Qt/6.2.1/gcc_64/lib/cmake/Qt6CoreTools -DQt6GuiTools_DIR=$HOME/Qt/6.2.1/gcc_64/lib/cmake/Qt6GuiTools -DQt6WidgetsTools_DIR=$HOME/Qt/6.2.1/gcc_64/lib/cmake/Qt6WidgetsTools ..
    - sh: cmake --build . --verbose --config ${CONFIGURATION}
