version: 1.1.0.{build}-{branch}
image: Visual Studio 2019

configuration:
  - Debug

platform:
  - x64

environment:
  matrix:
    - job_name: VS 2019 build
    - job_name: Clang 10 build

matrix:
  fast_finish: true

cache: C:/Tools/vcpkg/installed/

before_build:
  - vcpkg install libpng:x64-windows
  - mkdir build
  - cd build

for:
  -
    matrix:
      only:
        - job_name: VS 2019 build

    build_script:
    - cmd: cmake -DCMAKE_TOOLCHAIN_FILE=C:/Tools/vcpkg/scripts/buildsystems/vcpkg.cmake -DQt5_DIR=C:/Qt/5.15.0/msvc2019_64 -G "Visual Studio 16 2019" ..
    - cmd: cmake --build . --verbose --config %CONFIGURATION%

  -
    matrix:
      only:
        - job_name: Clang 10 build

    build_script:
    - cmd: cmake -DCMAKE_TOOLCHAIN_FILE=C:/Tools/vcpkg/scripts/buildsystems/vcpkg.cmake -DCMAKE_CXX_COMPILER=Clang -DQt5_DIR=C:/Qt/5.15.0/msvc2019_64 -G "Visual Studio 16 2019" ..
    - cmd: cmake --build . --verbose --config %CONFIGURATION%

test_script:
- cmd: ctest --verbose -C %CONFIGURATION%
