[Song]
;
name = 2112 Pt. 7 - Grand Finale
artist = Rush
album = 2112
genre = Prog Rock
year = 1976
song_length = 134933
diff_band = 3
diff_guitar = 4
diff_bass = 3
diff_drums = 5
diff_keys = -1
diff_guitarghl = -1
diff_bassghl = -1
preview_start_time = -1
frets = <color=orange>Neversoft</color>
charter=<color=orange>Neversoft</color>
icon = ghwor
album_track = 16000
playlist_track = 87
delay = 0
loading_phrase = 21:12 is military time for 9:12. 9/12 is September 12, Neil Peart's birthday.
