name: Compiler Warnings

on: push

jobs:
  msvc:
    runs-on: windows-2022
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          submodules: true

      - name: Install Qt
        uses: jurplel/install-qt-action@v3
        with:
          version: 6.5.*

      - name: Install other dependencies
        run: vcpkg install boost-test libpng

      - name: Make build directory
        run: mkdir build

      - name: Generate build files
        working-directory: build
        env:
          CMAKE_GENERATOR: "Visual Studio 17 2022"
          CMAKE_TOOLCHAIN_FILE: "C:/vcpkg/scripts/buildsystems/vcpkg.cmake"
        run: cmake ..

      - name: Build
        working-directory: build
        run: cmake --build . --verbose

  apple-clang:
    runs-on: macos-12
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          submodules: true

      - name: Install Qt
        uses: jurplel/install-qt-action@v3
        with:
          version: 6.4.*

      - name: Install Boost
        run: brew install boost

      - name: Make build directory
        run: mkdir build

      - name: Generate build files
        working-directory: build
        run: cmake ..

      - name: Build
        working-directory: build
        run: cmake --build . --verbose

  linux-gcc:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          submodules: true

      - name: Install Qt
        uses: jurplel/install-qt-action@v3
        with:
          version: 6.5.*

      - name: Install Boost Test
        run: vcpkg install boost-test

      - name: Make build directory
        run: mkdir build

      - name: Generate build files
        working-directory: build
        env:
          CMAKE_TOOLCHAIN_FILE: /usr/local/share/vcpkg/scripts/buildsystems/vcpkg.cmake
          CXX: g++-13
        run: cmake ..

      - name: Build
        working-directory: build
        run: cmake --build . --verbose
