name: Compiler Warnings

on: push

jobs:
  msvc:
    runs-on: windows-2022
    steps:
      - name: Checkout
        uses: actions/checkout@v5
        with:
          submodules: true

      - name: Install Qt
        uses: jurplel/install-qt-action@v4
        with:
          version: 6.7.2

      - name: Install other dependencies
        run: vcpkg install boost-locale boost-test libpng

      - name: Make build directory
        run: mkdir build

      - name: Generate build files
        working-directory: build
        env:
          CMAKE_GENERATOR: "Visual Studio 17 2022"
          CMAKE_TOOLCHAIN_FILE: "C:/vcpkg/scripts/buildsystems/vcpkg.cmake"
        run: cmake ..

      - name: Build
        working-directory: build
        run: cmake --build . --verbose

  apple-clang:
    runs-on: macos-14
    steps:
      - name: Checkout
        uses: actions/checkout@v5
        with:
          submodules: true

      - name: Install Qt
        uses: jurplel/install-qt-action@v4
        with:
          version: 6.7.2

      - name: Install Boost
        run: brew install boost

      - name: Make build directory
        run: mkdir build

      - name: Generate build files
        working-directory: build
        run: cmake ..

      - name: Build
        working-directory: build
        run: cmake --build . --verbose

  linux-gcc:
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout
        uses: actions/checkout@v5
        with:
          submodules: true

      - name: Install libpng
        run: |
          sudo apt-get update
          sudo apt-get install -y libpng-dev

      - name: Install Qt
        uses: jurplel/install-qt-action@v4
        with:
          version: 6.6.*

      - name: Install Boost dependencies
        run: vcpkg install boost-locale boost-test

      - name: Make build directory
        run: mkdir build

      - name: Generate build files
        working-directory: build
        env:
          CMAKE_TOOLCHAIN_FILE: /usr/local/share/vcpkg/scripts/buildsystems/vcpkg.cmake
          CXX: g++-14
        run: cmake ..

      - name: Build
        working-directory: build
        run: cmake --build . --verbose
