name: Compiler Warnings

on: push

jobs:
  msvc:
    runs-on: windows-2022
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          submodules: true

      - name: Install Qt
        uses: jurplel/install-qt-action@v3
        with:
          version: 6.5.*

      - name: Install other dependencies
        run: vcpkg --triplet x64-windows install boost-json boost-nowide boost-test libpng

      - name: Make build directory
        run: mkdir build

      - name: Generate build files
        working-directory: build
        env:
          CMAKE_GENERATOR: "Visual Studio 17 2022"
          CMAKE_TOOLCHAIN_FILE: "C:/vcpkg/scripts/buildsystems/vcpkg.cmake"
        run: cmake ..

      - name: Build
        working-directory: build
        run: cmake --build . --verbose

  apple-clang:
    runs-on: macos-12
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          submodules: true

      - name: Install Qt
        uses: jurplel/install-qt-action@v3
        with:
          version: 6.4.*

      - name: Install Boost
        run: brew install boost

      - name: Make build directory
        run: mkdir build

      - name: Generate build files
        working-directory: build
        run: cmake ..

      - name: Build
        working-directory: build
        run: cmake --build . --verbose

  linux-gcc:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          submodules: true

      - name: Install Qt
        uses: jurplel/install-qt-action@v3
        with:
          version: 6.5.*

      - name: Install Boost 1.84.0
        run: |
          wget -O "$HOME/boost_1_84_0.tar.bz2" https://boostorg.jfrog.io/artifactory/main/release/1.84.0/source/boost_1_84_0.tar.bz2
          tar --bzip2 -xf "$HOME/boost_1_84_0.tar.bz2" -C "$HOME"
          cd "$HOME/boost_1_84_0"
          ./bootstrap.sh --with-libraries=json,nowide,test --prefix=.
          ./b2 toolset=gcc-13 install > /dev/null

      - name: Make build directory
        run: mkdir build

      - name: Generate build files
        working-directory: build
        env:
          BOOST_ROOT: ~/boost_1_84_0
          CXX: g++-13
        run: cmake ..

      - name: Build
        working-directory: build
        run: cmake --build . --verbose
