name: Static Analysis

on: push

permissions: {}

jobs:
  clang-tidy:
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout
        uses: actions/checkout@v6
        with:
          submodules: true

      - name: Install libpng
        run: |
          sudo apt-get update
          sudo apt-get install -y libpng-dev

      - name: Install Qt
        uses: jurplel/install-qt-action@v4
        with:
          version: 6.6.*

      - name: Install Boost dependencies
        run: vcpkg install boost-graph boost-locale boost-test

      - name: Install clang-tidy 22
        run: |
          wget -O - https://apt.llvm.org/llvm-snapshot.gpg.key | sudo apt-key add -
          sudo add-apt-repository "deb http://apt.llvm.org/noble/ llvm-toolchain-noble-22 main"
          sudo apt-get update
          sudo apt-get install clang-tidy-22

      - name: Make build directory
        run: mkdir build

      - name: Generate build files
        working-directory: build
        env:
          CMAKE_TOOLCHAIN_FILE: /usr/local/share/vcpkg/scripts/buildsystems/vcpkg.cmake
          CXX: g++-14
        run: cmake -DCMAKE_EXPORT_COMPILE_COMMANDS=ON -DPACKAGE_TESTS=ON ..

      - name: Build moc files
        working-directory: build
        run: cmake --build . --target choptgui --verbose

      - name: Run clang tidy
        run: run-clang-tidy-22 -p=build/ -source-filter='^(?!.*(_autogen|extern)).*$' -hide-progress -quiet

  clang-format:
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout
        uses: actions/checkout@v6

      - name: Install clang-format 22
        run: |
          wget -O - https://apt.llvm.org/llvm-snapshot.gpg.key | sudo apt-key add -
          sudo add-apt-repository "deb http://apt.llvm.org/noble/ llvm-toolchain-noble-22 main"
          sudo apt-get update
          sudo apt-get install clang-format-22

      - name: Format
        run: |
          clang-format-22 -i gui/*.hpp gui/*.cpp include/*.hpp src/*.cpp tests/*.cpp tests/*.hpp
          git diff --color --exit-code
