name: tests

on: push

jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Install Boost 1.81.0
        run: |
          wget -O "$HOME/boost_1_81_0.tar.bz2" https://boostorg.jfrog.io/artifactory/main/release/1.81.0/source/boost_1_81_0.tar.bz2
          tar --bzip2 -xf "$HOME/boost_1_81_0.tar.bz2" -C "$HOME"
          cd "$HOME/boost_1_81_0"
          export CC=gcc-10
          export CXX=g++-10
          ./bootstrap.sh --with-libraries=json,nowide,program_options,test --prefix=.
          ./b2 install > /dev/null
      - name: Build
        run: |
          mkdir build
          cmake -DBUILD_GUI=OFF -DCMAKE_CXX_COMPILER=g++-10 -DBOOST_ROOT=$HOME/boost_1_81_0 .
          cmake --build build/ --verbose --config Debug