name: Tests

on: push

jobs:
  unit-tests:
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          submodules: true

      - name: Install libpng
        run: |
          sudo apt-get update
          sudo apt-get install -y libpng-dev

      - name: Install Qt
        uses: jurplel/install-qt-action@v4
        with:
          version: 6.6.*

      - name: Install Boost Test
        run: vcpkg install boost-test

      - name: Make build directory
        run: mkdir build

      - name: Generate build files
        working-directory: build
        env:
          CMAKE_TOOLCHAIN_FILE: /usr/local/share/vcpkg/scripts/buildsystems/vcpkg.cmake
          CXX: g++-14
        run: cmake -DBUILD_GUI=OFF ..

      - name: Build
        working-directory: build
        run: cmake --build . --verbose

      - name: Run unit tests
        working-directory: build
        run: ctest --verbose

  integration-tests:
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          submodules: true

      - name: Install libpng
        run: |
          sudo apt-get update
          sudo apt-get install -y libpng-dev

      - name: Install Qt
        uses: jurplel/install-qt-action@v4
        with:
          version: 6.6.*

      - name: Make build directory
        run: mkdir build

      - name: Generate build files
        working-directory: build
        env:
          CXX: g++-14
        run: cmake -DBUILD_GUI=OFF -DPACKAGE_TESTS=OFF ..

      - name: Build
        working-directory: build
        run: cmake --build . --verbose

      - name: Integration tests
        run: python3 integration_tests/run_integration_tests.py
